import 'package:flutter/material.dart';

class graphM extends StatefulWidget {
  const graphM({super.key});

  @override
  State<graphM> createState() => _graphMState();
}

class _graphMState extends State<graphM> {

  List<Map<String, dynamic>> dataMin3SD = [
    {'bulan' : 2, 'BB' : 1},
    {'bulan' : 2, 'BB' : 9},
    {'bulan' : 3, 'BB' : 8},
    {'bulan' : 4, 'BB' : 4},
    {'bulan' : 4, 'BB' : 9},
    {'bulan' : 5, 'BB' : 3},
    {'bulan' : 5, 'BB' : 7},
    {'bulan' : 5, 'BB' : 9},
    {'bulan' : 6, 'BB' : 2},
    {'bulan' : 6, 'BB' : 4},
    {'bulan' : 6, 'BB' : 6},
    {'bulan' : 6, 'BB' : 8},
    {'bulan' : 6, 'BB' : 9},
    {'bulan' : 7, 'BB' : 1},
    {'bulan' : 7, 'BB' : 2},
    {'bulan' : 7, 'BB' : 4},
    {'bulan' : 7, 'BB' : 5},
    {'bulan' : 7, 'BB' : 7},
    {'bulan' : 7, 'BB' : 8},
    {'bulan' : 8, 'BB' : 0},
    {'bulan' : 8, 'BB' : 1},
    {'bulan' : 8, 'BB' : 2},
    {'bulan' : 8, 'BB' : 4},
    {'bulan' : 8, 'BB' : 5},
    {'bulan' : 8, 'BB' : 6},
    {'bulan' : 8, 'BB' : 8},
    {'bulan' : 8, 'BB' : 9},
    {'bulan' : 9, 'BB' : 0},
    {'bulan' : 9, 'BB' : 1},
    {'bulan' : 9, 'BB' : 2},
    {'bulan' : 9, 'BB' : 4},
    {'bulan' : 9, 'BB' : 5},
    {'bulan' : 9, 'BB' : 6},
    {'bulan' : 9, 'BB' : 7},
    {'bulan' : 9, 'BB' : 8},
    {'bulan' : 9, 'BB' : 9},
    {'bulan' : 10, 'BB' : 0},
    {'bulan' : 10, 'BB' : 1},
    {'bulan' : 10, 'BB' : 2},
    {'bulan' : 10, 'BB' : 3},
    {'bulan' : 10, 'BB' : 4},
    {'bulan' : 10, 'BB' : 5},
    {'bulan' : 10, 'BB' : 6},
    {'bulan' : 10, 'BB' : 8},
    {'bulan' : 10, 'BB' : 9},
    {'bulan' : 11, 'BB' : 0},
    {'bulan' : 11, 'BB' : 1},
    {'bulan' : 11, 'BB' : 2},
    {'bulan' : 11, 'BB' : 3},
    {'bulan' : 11, 'BB' : 4},
    {'bulan' : 11, 'BB' : 5},
    {'bulan' : 11, 'BB' : 6},
    {'bulan' : 11, 'BB' : 7},
    {'bulan' : 11, 'BB' : 8},
    {'bulan' : 11, 'BB' : 9},
    {'bulan' : 12, 'BB' : 0},
    {'bulan' : 12, 'BB' : 1},
    {'bulan' : 12, 'BB' : 2},
    {'bulan' : 12, 'BB' : 3},
    {'bulan' : 12, 'BB' : 4},
  ];

  List<Map<String, dynamic>> dataMin2SD = [
    {'bulan' :2, 'BB' :5},
    {'bulan' :3, 'BB' :4},
    {'bulan' :4, 'BB' :3},
    {'bulan' :5, 'BB' :0},
    {'bulan' :5, 'BB' :6},
    {'bulan' :6, 'BB' :0},
    {'bulan' :6, 'BB' :4},
    {'bulan' :6, 'BB' :7},
    {'bulan' :6, 'BB' :9},
    {'bulan' :7, 'BB' :1},
    {'bulan' :7, 'BB' :4},
    {'bulan' :7, 'BB' :6},
    {'bulan' :7, 'BB' :7},
    {'bulan' :7, 'BB' :9},
    {'bulan' :8, 'BB' :1},
    {'bulan' :8, 'BB' :3},
    {'bulan' :8, 'BB' :4},
    {'bulan' :8, 'BB' :6},
    {'bulan' :8, 'BB' :8},
    {'bulan' :8, 'BB' :9},
    {'bulan' :9, 'BB' :1},
    {'bulan' :9, 'BB' :2},
    {'bulan' :9, 'BB' :4},
    {'bulan' :9, 'BB' :5},
    {'bulan' :9, 'BB' :7},
    {'bulan' :9, 'BB' :8},
    {'bulan' :10, 'BB' :0},
    {'bulan' :10, 'BB' :1},
    {'bulan' :10, 'BB' :2},
    {'bulan' :10, 'BB' :4},
    {'bulan' :10, 'BB' :5},
    {'bulan' :10, 'BB' :7},
    {'bulan' :10, 'BB' :8},
    {'bulan' :10, 'BB' :9},
    {'bulan' :11, 'BB' :0},
    {'bulan' :11, 'BB' :2},
    {'bulan' :11, 'BB' :3},
    {'bulan' :11, 'BB' :4},
    {'bulan' :11, 'BB' :5},
    {'bulan' :11, 'BB' :6},
    {'bulan' :11, 'BB' :8},
    {'bulan' :11, 'BB' :9},
    {'bulan' :12, 'BB' :0},
    {'bulan' :12, 'BB' :1},
    {'bulan' :12, 'BB' :2},
    {'bulan' :12, 'BB' :4},
    {'bulan' :12, 'BB' :5},
    {'bulan' :12, 'BB' :6},
    {'bulan' :12, 'BB' :7},
    {'bulan' :12, 'BB' :8},
    {'bulan' :12, 'BB' :9},
    {'bulan' :13, 'BB' :1},
    {'bulan' :13, 'BB' :2},
    {'bulan' :13, 'BB' :3},
    {'bulan' :13, 'BB' :4},
    {'bulan' :13, 'BB' :5},
    {'bulan' :13, 'BB' :6},
    {'bulan' :13, 'BB' :7},
    {'bulan' :13, 'BB' :8},
    {'bulan' :14, 'BB' :0},
    {'bulan' :14, 'BB' :1},
  ];

  List<Map<String, dynamic>> dataMin1SD = [
    {'bulan' :2, 'BB' :9},
    {'bulan' :3, 'BB' :9},
    {'bulan' :4, 'BB' :9},
    {'bulan' :5, 'BB' :7},
    {'bulan' :6, 'BB' :2},
    {'bulan' :6, 'BB' :7},
    {'bulan' :7, 'BB' :1},
    {'bulan' :7, 'BB' :4},
    {'bulan' :7, 'BB' :7},
    {'bulan' :8, 'BB' :0},
    {'bulan' :8, 'BB' :2},
    {'bulan' :8, 'BB' :4},
    {'bulan' :8, 'BB' :6},
    {'bulan' :8, 'BB' :8},
    {'bulan' :9, 'BB' :0},
    {'bulan' :9, 'BB' :2},
    {'bulan' :9, 'BB' :4},
    {'bulan' :9, 'BB' :6},
    {'bulan' :9, 'BB' :8},
    {'bulan' :10, 'BB' :0},
    {'bulan' :10, 'BB' :1},
    {'bulan' :10, 'BB' :3},
    {'bulan' :10, 'BB' :5},
    {'bulan' :10, 'BB' :7},
    {'bulan' :10, 'BB' :8},
    {'bulan' :11, 'BB' :0},
    {'bulan' :11, 'BB' :2},
    {'bulan' :11, 'BB' :3},
    {'bulan' :11, 'BB' :5},
    {'bulan' :11, 'BB' :7},
    {'bulan' :11, 'BB' :8},
    {'bulan' :12, 'BB' :0},
    {'bulan' :12, 'BB' :1},
    {'bulan' :12, 'BB' :3},
    {'bulan' :12, 'BB' :4},
    {'bulan' :12, 'BB' :6},
    {'bulan' :12, 'BB' :7},
    {'bulan' :12, 'BB' :9},
    {'bulan' :13, 'BB' :0},
    {'bulan' :13, 'BB' :1},
    {'bulan' :13, 'BB' :3},
    {'bulan' :13, 'BB' :4},
    {'bulan' :13, 'BB' :6},
    {'bulan' :13, 'BB' :7},
    {'bulan' :13, 'BB' :8},
    {'bulan' :14, 'BB' :0},
    {'bulan' :14, 'BB' :1},
    {'bulan' :14, 'BB' :3},
    {'bulan' :14, 'BB' :4},
    {'bulan' :14, 'BB' :5},
    {'bulan' :14, 'BB' :7},
    {'bulan' :14, 'BB' :8},
    {'bulan' :15, 'BB' :0},
    {'bulan' :15, 'BB' :1},
    {'bulan' :15, 'BB' :2},
    {'bulan' :15, 'BB' :4},
    {'bulan' :15, 'BB' :5},
    {'bulan' :15, 'BB' :6},
    {'bulan' :15, 'BB' :8},
    {'bulan' :15, 'BB' :9},
    {'bulan' :16, 'BB' :0},
  ];

  List<Map<String, dynamic>> dataMedian = [
    {'bulan' :3, 'BB' :3},
    {'bulan' :4, 'BB' :5},
    {'bulan' :5, 'BB' :6},
    {'bulan' :6, 'BB' :4},
    {'bulan' :7, 'BB' :0},
    {'bulan' :7, 'BB' :5},
    {'bulan' :7, 'BB' :9},
    {'bulan' :8, 'BB' :3},
    {'bulan' :8, 'BB' :6},
    {'bulan' :8, 'BB' :9},
    {'bulan' :9, 'BB' :2},
    {'bulan' :9, 'BB' :4},
    {'bulan' :9, 'BB' :6},
    {'bulan' :9, 'BB' :9},
    {'bulan' :10, 'BB' :1},
    {'bulan' :10, 'BB' :3},
    {'bulan' :10, 'BB' :5},
    {'bulan' :10, 'BB' :7},
    {'bulan' :10, 'BB' :9},
    {'bulan' :11, 'BB' :1},
    {'bulan' :11, 'BB' :3},
    {'bulan' :11, 'BB' :5},
    {'bulan' :11, 'BB' :8},
    {'bulan' :12, 'BB' :0},
    {'bulan' :12, 'BB' :2},
    {'bulan' :12, 'BB' :4},
    {'bulan' :12, 'BB' :5},
    {'bulan' :12, 'BB' :7},
    {'bulan' :12, 'BB' :9},
    {'bulan' :13, 'BB' :1},
    {'bulan' :13, 'BB' :3},
    {'bulan' :13, 'BB' :5},
    {'bulan' :13, 'BB' :7},
    {'bulan' :13, 'BB' :8},
    {'bulan' :14, 'BB' :0},
    {'bulan' :14, 'BB' :2},
    {'bulan' :14, 'BB' :3},
    {'bulan' :14, 'BB' :5},
    {'bulan' :14, 'BB' :7},
    {'bulan' :14, 'BB' :8},
    {'bulan' :15, 'BB' :0},
    {'bulan' :15, 'BB' :2},
    {'bulan' :15, 'BB' :3},
    {'bulan' :15, 'BB' :5},
    {'bulan' :15, 'BB' :7},
    {'bulan' :15, 'BB' :8},
    {'bulan' :16, 'BB' :0},
    {'bulan' :16, 'BB' :2},
    {'bulan' :16, 'BB' :3},
    {'bulan' :16, 'BB' :5},
    {'bulan' :16, 'BB' :7},
    {'bulan' :16, 'BB' :8},
    {'bulan' :17, 'BB' :0},
    {'bulan' :17, 'BB' :2},
    {'bulan' :17, 'BB' :3},
    {'bulan' :17, 'BB' :5},
    {'bulan' :17, 'BB' :7},
    {'bulan' :17, 'BB' :8},
    {'bulan' :18, 'BB' :0},
    {'bulan' :18, 'BB' :2},
    {'bulan' :18, 'BB' :3},
  ];

  @override
  Widget build(BuildContext context) {
    return const Placeholder();
  }
}