// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMwhrQZHH4QvehbVNOXnSmMsm9cryRrew',
    appId: '1:963193074662:web:ce594bdb4da7dae1fd1c27',
    messagingSenderId: '963193074662',
    projectId: 'sipanda-8ad69',
    authDomain: 'sipanda-8ad69.firebaseapp.com',
    storageBucket: 'sipanda-8ad69.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIYJS1x_G51kN10knrv1nVvVDbKjsru2w',
    appId: '1:963193074662:android:7b7463e74952da44fd1c27',
    messagingSenderId: '963193074662',
    projectId: 'sipanda-8ad69',
    storageBucket: 'sipanda-8ad69.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzZJKx-kEZl9b58C0MlljPms6iEIxOp5Y',
    appId: '1:963193074662:ios:dc097ed9c6df5aa1fd1c27',
    messagingSenderId: '963193074662',
    projectId: 'sipanda-8ad69',
    storageBucket: 'sipanda-8ad69.appspot.com',
    iosBundleId: 'com.example.sipanda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzZJKx-kEZl9b58C0MlljPms6iEIxOp5Y',
    appId: '1:963193074662:ios:dc097ed9c6df5aa1fd1c27',
    messagingSenderId: '963193074662',
    projectId: 'sipanda-8ad69',
    storageBucket: 'sipanda-8ad69.appspot.com',
    iosBundleId: 'com.example.sipanda',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMwhrQZHH4QvehbVNOXnSmMsm9cryRrew',
    appId: '1:963193074662:web:26c27fdbed076abefd1c27',
    messagingSenderId: '963193074662',
    projectId: 'sipanda-8ad69',
    authDomain: 'sipanda-8ad69.firebaseapp.com',
    storageBucket: 'sipanda-8ad69.appspot.com',
  );

}