// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWkbLu1yhUrsIdT_8KJTaUwgfel_yihYs',
    appId: '1:136176657126:web:04d1002a94e856e15d5127',
    messagingSenderId: '136176657126',
    projectId: 'sipanda-847b0',
    authDomain: 'sipanda-847b0.firebaseapp.com',
    storageBucket: 'sipanda-847b0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYMFfgPC85ob_y3lzUzzsiwrlpycExdRA',
    appId: '1:136176657126:android:07ee385b3b1646345d5127',
    messagingSenderId: '136176657126',
    projectId: 'sipanda-847b0',
    storageBucket: 'sipanda-847b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMewQUst2-STlDHvdZ0r41vhXaW0CYg_I',
    appId: '1:136176657126:ios:2854783498d4e3315d5127',
    messagingSenderId: '136176657126',
    projectId: 'sipanda-847b0',
    storageBucket: 'sipanda-847b0.appspot.com',
    iosBundleId: 'com.example.sipanda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMewQUst2-STlDHvdZ0r41vhXaW0CYg_I',
    appId: '1:136176657126:ios:2854783498d4e3315d5127',
    messagingSenderId: '136176657126',
    projectId: 'sipanda-847b0',
    storageBucket: 'sipanda-847b0.appspot.com',
    iosBundleId: 'com.example.sipanda',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWkbLu1yhUrsIdT_8KJTaUwgfel_yihYs',
    appId: '1:136176657126:web:a3aac2a2698fc7205d5127',
    messagingSenderId: '136176657126',
    projectId: 'sipanda-847b0',
    authDomain: 'sipanda-847b0.firebaseapp.com',
    storageBucket: 'sipanda-847b0.appspot.com',
  );

}