class BBMale{
  double bulan, score;
  String garis;

  BBMale({
    required this.bulan,
    required this.score,
    required this.garis
  });

  static List<BBMale> listBBMale = [
    BBMale(bulan :0, score :2.1, garis : '-3SD'),
    BBMale(bulan :1, score :2.9, garis : '-3SD'),
    BBMale(bulan :2, score :3.8, garis : '-3SD'),
    BBMale(bulan :3, score :4.4, garis : '-3SD'),
    BBMale(bulan :4, score :4.9, garis : '-3SD'),
    BBMale(bulan :5, score :5.3, garis : '-3SD'),
    BBMale(bulan :6, score :5.7, garis : '-3SD'),
    BBMale(bulan :7, score :5.9, garis : '-3SD'),
    BBMale(bulan :8, score :6.2, garis : '-3SD'),
    BBMale(bulan :9, score :6.4, garis : '-3SD'),
    BBMale(bulan :10, score :6.6, garis : '-3SD'),
    BBMale(bulan :11, score :6.8, garis : '-3SD'),
    BBMale(bulan :12, score :6.9, garis : '-3SD'),
    BBMale(bulan :13, score :7.1, garis : '-3SD'),
    BBMale(bulan :14, score :7.2, garis : '-3SD'),
    BBMale(bulan :15, score :7.4, garis : '-3SD'),
    BBMale(bulan :16, score :7.5, garis : '-3SD'),
    BBMale(bulan :17, score :7.7, garis : '-3SD'),
    BBMale(bulan :18, score :7.8, garis : '-3SD'),
    BBMale(bulan :19, score :8, garis : '-3SD'),
    BBMale(bulan :20, score :8.1, garis : '-3SD'),
    BBMale(bulan :21, score :8.2, garis : '-3SD'),
    BBMale(bulan :22, score :8.4, garis : '-3SD'),
    BBMale(bulan :23, score :8.5, garis : '-3SD'),
    BBMale(bulan :24, score :8.6, garis : '-3SD'),
    BBMale(bulan :25, score :8.8, garis : '-3SD'),
    BBMale(bulan :26, score :8.9, garis : '-3SD'),
    BBMale(bulan :27, score :9, garis : '-3SD'),
    BBMale(bulan :28, score :9.1, garis : '-3SD'),
    BBMale(bulan :29, score :9.2, garis : '-3SD'),
    BBMale(bulan :30, score :9.4, garis : '-3SD'),
    BBMale(bulan :31, score :9.5, garis : '-3SD'),
    BBMale(bulan :32, score :9.6, garis : '-3SD'),
    BBMale(bulan :33, score :9.7, garis : '-3SD'),
    BBMale(bulan :34, score :9.8, garis : '-3SD'),
    BBMale(bulan :35, score :9.9, garis : '-3SD'),
    BBMale(bulan :36, score :10, garis : '-3SD'),
    BBMale(bulan :37, score :10.1, garis : '-3SD'),
    BBMale(bulan :38, score :10.2, garis : '-3SD'),
    BBMale(bulan :39, score :10.3, garis : '-3SD'),
    BBMale(bulan :40, score :10.4, garis : '-3SD'),
    BBMale(bulan :41, score :10.5, garis : '-3SD'),
    BBMale(bulan :42, score :10.6, garis : '-3SD'),
    BBMale(bulan :43, score :10.7, garis : '-3SD'),
    BBMale(bulan :44, score :10.8, garis : '-3SD'),
    BBMale(bulan :45, score :10.9, garis : '-3SD'),
    BBMale(bulan :46, score :11, garis : '-3SD'),
    BBMale(bulan :47, score :11.1, garis : '-3SD'),
    BBMale(bulan :48, score :11.2, garis : '-3SD'),
    BBMale(bulan :49, score :11.3, garis : '-3SD'),
    BBMale(bulan :50, score :11.4, garis : '-3SD'),
    BBMale(bulan :51, score :11.5, garis : '-3SD'),
    BBMale(bulan :52, score :11.6, garis : '-3SD'),
    BBMale(bulan :53, score :11.7, garis : '-3SD'),
    BBMale(bulan :54, score :11.8, garis : '-3SD'),
    BBMale(bulan :55, score :11.9, garis : '-3SD'),
    BBMale(bulan :56, score :12, garis : '-3SD'),
    BBMale(bulan :57, score :12.1, garis : '-3SD'),
    BBMale(bulan :58, score :12.2, garis : '-3SD'),
    BBMale(bulan :59, score :12.3, garis : '-3SD'),
    BBMale(bulan :60, score :12.4, garis : '-3SD'),
  ];
}

